-- Run this once in the Supabase SQL Editor for KHMC admin password reset.
-- This table stores only SHA-256 hashes of reset tokens.
create table if not exists public.admin_password_resets (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admin_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_password_resets_admin_id_idx
  on public.admin_password_resets(admin_id);

create index if not exists admin_password_resets_expires_at_idx
  on public.admin_password_resets(expires_at);

alter table public.admin_password_resets enable row level security;

-- The application accesses this table only on the server with the Supabase service-role key.
-- No public RLS policy is required.
