-- Run this once in Supabase SQL Editor.
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  name text not null,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- The application uses the Supabase service-role key on the server,
-- so no public RLS policy is needed for this table.
