'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import './admin.css';

const statuses = ['New', 'In Review', 'Resolved'] as const;
type Status = (typeof statuses)[number];
type Filter = 'All' | Status;
type Suggestion = {
  id: number; type?: string; department?: string; message?: string; anonymous?: boolean;
  name?: string; phone?: string; created_at?: string; status?: Status;
};

function Icon({ children }: { children: React.ReactNode }) { return <span className="navIcon" aria-hidden="true">{children}</span>; }

export default function Admin() {
  const [items, setItems] = useState<Suggestion[]>([]); const [loading, setLoading] = useState(true); const [loggedIn, setLoggedIn] = useState(false);
  const [password, setPassword] = useState(''); const [loginError, setLoginError] = useState(''); const [loadError, setLoadError] = useState('');
  const [filter, setFilter] = useState<Filter>('All'); const [search, setSearch] = useState(''); const [department, setDepartment] = useState('All departments'); const [lastUpdated, setLastUpdated] = useState<Date | null>(null);

  async function load() {
    setLoading(true); setLoadError('');
    try { const r = await fetch('/api/admin/suggestions?ts=' + Date.now(), { cache: 'no-store' }); const text = await r.text(); let d: { suggestions?: Suggestion[]; error?: string } = {}; try { d = text ? JSON.parse(text) : {}; } catch {}
      if (r.status === 401) { setLoggedIn(false); return; } if (!r.ok) throw new Error(d.error || `Unable to load suggestions (HTTP ${r.status})`); if (!Array.isArray(d.suggestions)) throw new Error('Invalid response from admin API');
      setItems(d.suggestions); setLoggedIn(true); setLastUpdated(new Date());
    } catch (error) { console.error('Admin load error:', error); setLoadError(error instanceof Error ? error.message : 'Unable to load suggestions'); setLoggedIn(true); } finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);
  async function login(e: FormEvent) { e.preventDefault(); setLoginError(''); try { const r = await fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); const d = await r.json(); if (!r.ok) { setLoginError(d.error || 'Login failed'); return; } setPassword(''); await load(); } catch (error) { setLoginError(error instanceof Error ? error.message : 'Login failed'); } }
  async function updateStatus(id: number, status: string) { const r = await fetch('/api/admin/suggestions', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); if (r.ok) setItems(prev => prev.map(x => x.id === id ? { ...x, status: status as Status } : x)); }
  async function remove(id: number) { if (!confirm('Delete this suggestion permanently?')) return; const r = await fetch('/api/admin/suggestions', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); if (r.ok) setItems(prev => prev.filter(x => x.id !== id)); }
  async function logout() { await fetch('/api/admin/login', { method: 'DELETE' }); setLoggedIn(false); }

  const counts = useMemo(() => ({ All: items.length, New: items.filter(x => !x.status || x.status === 'New').length, 'In Review': items.filter(x => x.status === 'In Review').length, Resolved: items.filter(x => x.status === 'Resolved').length }), [items]);
  const departments = useMemo(() => { const values = items.map(x => x.department).filter(Boolean) as string[]; return ['All departments', ...Array.from(new Set(values)).sort()]; }, [items]);
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return items.filter(x => { const status = x.status || 'New'; const matchesStatus = filter === 'All' || status === filter; const matchesDepartment = department === 'All departments' || (x.department || 'General') === department; const haystack = [x.type, x.department, x.message, x.name, x.phone].filter(Boolean).join(' ').toLowerCase(); return matchesStatus && matchesDepartment && (!q || haystack.includes(q)); }); }, [items, filter, department, search]);
  const departmentStats = useMemo(() => { const map = new Map<string, number>(); items.forEach(x => { const d = x.department || 'General'; map.set(d, (map.get(d) || 0) + 1); }); return [...map.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5); }, [items]);
  const maxDepartment = Math.max(1, ...departmentStats.map(x => x[1])); const resolvedPercent = counts.All ? Math.round((counts.Resolved / counts.All) * 100) : 0;

  if (!loggedIn) return <main className="admin loginPage"><div className="loginCard"><img src="/khmc-logo.png" alt="KivuHills Medical Center" className="loginLogo"/><div className="loginIcon">✓</div><div className="eyebrow">KHMC ADMINISTRATION</div><h1>Admin Dashboard</h1><p>Sign in securely to review and manage patient feedback.</p><form onSubmit={login} className="loginForm"><label>Admin password<input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter password" required /></label>{loginError && <div className="error">{loginError}</div>}<button type="submit">Sign in to dashboard</button></form><a href="/">← Back to patient form</a></div></main>;

  return <main className="adminShell"><aside className="sidebar"><div className="sidebarBrand"><img src="/khmc-logo.png" alt="KivuHills Medical Center"/></div><div className="sideLabel">WORKSPACE</div><nav>
    <button className="navItem active"><Icon>⌂</Icon><span>Dashboard</span></button><button className="navItem" onClick={() => setFilter('All')}><Icon>☷</Icon><span>All suggestions</span><b>{counts.All}</b></button>
    <button className={`navItem ${filter === 'New' ? 'selected' : ''}`} onClick={() => setFilter('New')}><Icon>●</Icon><span>New</span><b className="orange">{counts.New}</b></button>
    <button className={`navItem ${filter === 'In Review' ? 'selected' : ''}`} onClick={() => setFilter('In Review')}><Icon>◷</Icon><span>In review</span><b className="blue">{counts['In Review']}</b></button>
    <button className={`navItem ${filter === 'Resolved' ? 'selected' : ''}`} onClick={() => setFilter('Resolved')}><Icon>✓</Icon><span>Resolved</span><b className="green">{counts.Resolved}</b></button><button className="navItem" onClick={load}><Icon>↻</Icon><span>Refresh data</span></button>
  </nav><div className="sidebarBottom"><div className="feedbackNote"><span>♥</span><strong>Patient voice matters</strong><small>Use feedback to improve care and service.</small></div><div className="adminProfile"><div className="profileAvatar">A</div><div><strong>Administrator</strong><small>KHMC Suggestion Box</small></div><span>⌄</span></div></div></aside>

  <section className="adminMain"><header className="topbar"><div><span className="mobileBrand">KHMC</span><span className="topContext">Suggestion Box / Dashboard</span></div><div className="topActions"><span className="online"><i/> System online</span><a href="/">Patient Form</a><button className="logout" onClick={logout}>Sign out</button></div></header>
  <div className="content"><section className="dashboardHero"><div><div className="eyebrow">KHMC • FEEDBACK MANAGEMENT</div><h1>Good day, Administrator</h1><p>Monitor patient feedback, prioritize new messages and track what has been resolved.</p></div><div className="heroActions"><button className="outlineButton" onClick={load} disabled={loading}>↻ {loading ? 'Refreshing…' : 'Refresh'}</button><a className="primaryButton" href="/">Open patient form ↗</a></div></section>

  <section className="dashboardStats" aria-label="Suggestion summary"><button className={`statCard ${filter === 'All' ? 'active' : ''}`} onClick={() => setFilter('All')}><span className="statIcon">☷</span><span className="statLabel">All suggestions</span><strong>{counts.All}</strong><small>Total received</small></button><button className={`statCard ${filter === 'New' ? 'active' : ''}`} onClick={() => setFilter('New')}><span className="statIcon warm">●</span><span className="statLabel">New</span><strong>{counts.New}</strong><small>Need attention</small></button><button className={`statCard ${filter === 'In Review' ? 'active' : ''}`} onClick={() => setFilter('In Review')}><span className="statIcon cool">◷</span><span className="statLabel">In review</span><strong>{counts['In Review']}</strong><small>Being handled</small></button><button className={`statCard ${filter === 'Resolved' ? 'active' : ''}`} onClick={() => setFilter('Resolved')}><span className="statIcon good">✓</span><span className="statLabel">Resolved</span><strong>{counts.Resolved}</strong><small>{resolvedPercent}% of total</small></button></section>

  <section className="workspace"><div className="workspaceHead"><div><h2>Patient feedback</h2><p>{filtered.length} {filtered.length === 1 ? 'message' : 'messages'} shown {lastUpdated ? `• Updated ${lastUpdated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : ''}</p></div><div className="queueBadge"><span/> Live queue</div></div><div className="toolbar"><div className="searchBox"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search messages, departments or names…"/></div><select value={department} onChange={e => setDepartment(e.target.value)} aria-label="Filter by department">{departments.map(d => <option key={d}>{d}</option>)}</select><select value={filter} onChange={e => setFilter(e.target.value as Filter)} aria-label="Filter by status"><option>All</option>{statuses.map(s => <option key={s}>{s}</option>)}</select></div>
  {loading ? <div className="empty"><div className="loadingDot">•</div><h2>Loading feedback</h2><p>Fetching the latest patient messages…</p></div> : loadError ? <div className="empty"><div className="emptyIcon">!</div><h2>Unable to load messages</h2><p>{loadError}</p><button onClick={load}>Try again</button></div> : filtered.length === 0 ? <div className="empty"><div className="emptyIcon">✓</div><h2>{items.length === 0 ? 'No suggestions yet' : 'No matching feedback'}</h2><p>{items.length === 0 ? 'New messages will appear here when patients submit the form.' : 'Try changing your search or filters.'}</p>{items.length > 0 && <button onClick={() => { setSearch(''); setDepartment('All departments'); setFilter('All'); }}>Clear filters</button>}</div> : <div className="tableWrap"><table><thead><tr><th>FEEDBACK</th><th>DEPARTMENT</th><th>FROM</th><th>STATUS</th><th>DATE</th><th>ACTION</th></tr></thead><tbody>{filtered.map(x => { const status = x.status || 'New'; return <tr key={x.id}><td><div className="feedbackCell"><span className={`feedbackIcon ${String(x.type || '').toLowerCase() === 'complaint' ? 'complaint' : ''}`}>{String(x.type || 'Suggestion').toLowerCase() === 'complaint' ? '!' : '✦'}</span><div><strong>{x.type || 'Suggestion'}</strong><p>{x.message || 'No message provided.'}</p><small>#{x.id}</small></div></div></td><td><span className="departmentPill">{x.department || 'General'}</span></td><td><div className="sender"><span className="avatar">{x.anonymous ? '?' : (x.name || 'P').charAt(0).toUpperCase()}</span><div><b>{x.anonymous ? 'Anonymous' : (x.name || 'No name')}</b><small>{x.anonymous ? 'Identity hidden' : (x.phone || 'No phone')}</small></div></div></td><td><select className={`statusSelect status-${status.toLowerCase().replace(' ', '-')}`} value={status} onChange={e => updateStatus(x.id, e.target.value)} aria-label={`Status for message ${x.id}`}>{statuses.map(s => <option key={s}>{s}</option>)}</select></td><td><span className="dateText">{x.created_at ? new Date(x.created_at).toLocaleDateString(undefined, { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}</span><small className="timeText">{x.created_at ? new Date(x.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''}</small></td><td><button className="delete" onClick={() => remove(x.id)} title="Delete suggestion">Delete</button></td></tr>; })}</tbody></table></div>}
  </section>

  <section className="insights"><div className="insightCard"><div className="insightHead"><div><h3>Feedback status</h3><p>Current distribution</p></div><span className="miniTotal">{counts.All} total</span></div><div className="statusBars"><div><span><b>New</b>{counts.New}</span><i><em style={{width:`${counts.All ? counts.New / counts.All * 100 : 0}%`}}/></i></div><div><span><b>In review</b>{counts['In Review']}</span><i><em style={{width:`${counts.All ? counts['In Review'] / counts.All * 100 : 0}%`}}/></i></div><div><span><b>Resolved</b>{counts.Resolved}</span><i><em style={{width:`${counts.All ? counts.Resolved / counts.All * 100 : 0}%`}}/></i></div></div></div><div className="insightCard"><div className="insightHead"><div><h3>Top departments</h3><p>Where feedback is coming from</p></div></div>{departmentStats.length === 0 ? <div className="noData">No department data yet.</div> : <div className="departmentBars">{departmentStats.map(([name,value]) => <div key={name}><span>{name}</span><b>{value}</b><i><em style={{width:`${value / maxDepartment * 100}%`}}/></i></div>)}</div>}</div><div className="insightCard quickCard"><div className="quickIcon">✦</div><div><h3>Keep the queue healthy</h3><p>{counts.New > 0 ? `You have ${counts.New} new ${counts.New === 1 ? 'message' : 'messages'} waiting for attention.` : 'There are no new messages waiting right now.'}</p></div><button onClick={() => setFilter('New')}>View new →</button></div></section><footer>© {new Date().getFullYear()} KivuHills Medical Center • Suggestion Box</footer></div></section></main>;
}
